  <!--Código por: Rodrigo Cano--> 
<?php
	if (!isset($_SESSION['cesta'])) {//Crea la sesion cesta en caso de no existir
		$cesta= [];
		$_SESSION['cesta'] = $cesta;//Se guarda un array vacio
		
	}
	if ($_SERVER["REQUEST_METHOD"] == "POST") {//Se añade un producto a la cesta
		if (isset($_POST['cesta'])) {
			$cancion = limpiar_campo($_POST["cancion"]);
			$count=count($_SESSION['cesta']);
			$cesta=$_SESSION['cesta'];
			$busqueda="SELECT * FROM Track WHERE Name=N'$cancion'";
			$UnitPrice=dato("UnitPrice", $busqueda);
			$cesta[$count][$cancion]=$UnitPrice;
			$_SESSION['cesta']=$cesta;
			}
	}

$_SESSION['usuario'] = "ftremblay@gmail.com";
//echo $_SESSION['usuario'];



	$TotalPrecio=0;
	if (isset($_SESSION['cesta']) && count($_SESSION['cesta'])>0 )
		$TotalPrecio=MostrarCesta($_SESSION['cesta']);

	
	if ($_SERVER["REQUEST_METHOD"] == "POST" ){
		if(isset($_POST['compraFin'])){
			if (count($_SESSION['cesta'])>0) {
				$correcto=true;
				$ahora = date('Y/m/d');
				$invoiceId=dato("InvoiceId", "SELECT * FROM Invoice");
				$invoiceId++;
				//Se obtiene los datos del usuario
				$busqueda="SELECT * FROM Customer WHERE Email=N'".$_SESSION['usuario']."'";
				$datosCliente=datos($busqueda);
				
				$NewInvoice="INSERT INTO Invoice (InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingCountry,BillingPostalCode,Total) VALUES ($invoiceId, ".$datosCliente["CustomerId"]." , '$ahora', N'".$datosCliente["Address"]."', N'".$datosCliente["City"]."', N'".$datosCliente["Country"]."', N'".$datosCliente["PostalCode"]."', $TotalPrecio)";
				$correcto=Ejecutar($NewInvoice);

				for ($i=0; $i < count($_SESSION['cesta']) ; $i++) { 
					$cesta=$_SESSION['cesta'][$i];
					foreach ($cesta as $cancion => $UnitPrice) {
					$InvoiceLineId=dato("InvoiceLineId", "SELECT * FROM InvoiceLine");
					$InvoiceLineId++;
					$TrackId=dato("TrackId", "SELECT * FROM Track");
					$TrackId++;
					$NewInvoiceLine="INSERT INTO InvoiceLine (InvoiceLineId,InvoiceId,TrackId,UnitPrice,Quantity) VALUES ($InvoiceLineId ,".$datosCliente["CustomerId"].",$TrackId , $UnitPrice, 1)";
					$correcto=Ejecutar($NewInvoiceLine);
				}
				}
				
				if ($correcto) {
					$_SESSION['cesta']= [];
					echo "<br>La compra se ha realizado correctamente";
					echo "<br><a href='downmusic.php'>Recargar Pagina</a>";
					
				}
				else{
					echo "<br>Hubo un error en el preceso";
					echo "<br><a href='downmusic.php'>Recargar Pagina</a>";
				}
			}
			else {
				echo "<br> No tienes ningun producto en la cesta";
				echo "<br><a href='downmusic.php'>Recargar Pagina</a>";
			}
		}
	}
	if(!isset($_POST['compraFin']))
	{
		echo "<h2> Musica <h2>";
		echo "<form name='alta_ped' action='downmusic.php' method='post'>";
		echo "<select name='cancion'>";
			    // Solo muestra datos no accede a los mismos
	            foreach ($canciones as $cancion) {
	                echo "<option>" . $cancion["Name"]. "</option>";
	            }
		echo "</select><br>";
		echo "<input type='submit' value='Añadir Cesta' name='cesta'>";
		echo "<input type='submit' value='Finalizar Compra' name='compraFin'>";

	}
	
?>

